# config for express or rest api

# service: to-doapp-dev
# provider:
#   name: aws
#   runtime: nodejs18.x
# functions:
#   app:
#     handler: build/src/app.handler
#     events:
#       - http: ANY /
#       - http: ANY /{proxy+}



# Config for graphQl Server
service: LoginService-GQL-Lambda
provider:
  name: aws
  runtime: nodejs16.x
  httpApi:
    cors: true
functions:
  graphql:
    # Make sure your file path is correct!
    # (e.g., if your file is in the root folder use server.graphqlHandler )
    # The format is: <FILENAME>.<HANDLER>
    handler: build/src/appServer.graphqlHandler
    events:
      - httpApi:
          path: /
          method: POST
      - httpApi:
          path: /
          method: GET
# Omit the following lines if you aren't using TS!
plugins:
  - serverless-plugin-typescript 